"""Hardcoded values for ``Settings`` presets."""

PRESET_HARDCODE = {
    # 'default' is handled by Settings.__init__().

    'legal': {
        'dim': (1700, 2800),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 200,
        'line_stroke': {
            -1: 4,
            0: 3,
            1: 3,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (0, 0, 0, 255),
            2: (64, 64, 64, 96),
            3: (64, 64, 64, 24),
            None: (230, 230, 230, 24)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 48,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 64,
        'footerfont_size': 28,
        'secfont_size': 36,
        'lotfont_size': 14,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 180,
        'header_px_above_body': 15,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 100,
        'footer_marg_right_x': 100,
        'footer_marg_bottom_y': 80,
        'footer_px_between_lines': 10,
        'write_header': True,
        'short_header': False,
        'write_tracts': True,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'legal_gray': {
        'dim': (1700, 2800),
        'qq_fill_rgba': (68, 68, 68, 100),
        'sec_length_px': 200,
        'line_stroke': {
            -1: 4,
            0: 3,
            1: 3,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (0, 0, 0, 255),
            2: (64, 64, 64, 96),
            3: (64, 64, 64, 24),
            None: (230, 230, 230, 24)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 48,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 64,
        'footerfont_size': 28,
        'secfont_size': 36,
        'lotfont_size': 14,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (68, 68, 68, 255),
        'body_marg_top_y': 180,
        'header_px_above_body': 15,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 100,
        'footer_marg_right_x': 100,
        'footer_marg_bottom_y': 80,
        'footer_px_between_lines': 10,
        'write_header': True,
        'short_header': False,
        'write_tracts': True,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'letter': {
        'dim': (1700, 2200),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 200,
        'line_stroke': {
            -1: 4,
            0: 3,
            1: 3,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (0, 0, 0, 255),
            2: (64, 64, 64, 96),
            3: (64, 64, 64, 24),
            None: (230, 230, 230, 24)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 48,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 64,
        'footerfont_size': 28,
        'secfont_size': 36,
        'lotfont_size': 14,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 180,
        'header_px_above_body': 15,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 100,
        'footer_marg_right_x': 100,
        'footer_marg_bottom_y': 80,
        'footer_px_between_lines': 10,
        'write_header': True,
        'short_header': False,
        'write_tracts': True,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'letter_gray': {
        'dim': (1700, 2200),
        'qq_fill_rgba': (68, 68, 68, 100),
        'sec_length_px': 200,
        'line_stroke': {
            -1: 4,
            0: 3,
            1: 3,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (0, 0, 0, 255),
            2: (64, 64, 64, 96),
            3: (64, 64, 64, 24),
            None: (230, 230, 230, 24)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 48,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 64,
        'footerfont_size': 28,
        'secfont_size': 36,
        'lotfont_size': 14,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (68, 68, 68, 255),
        'body_marg_top_y': 180,
        'header_px_above_body': 15,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 100,
        'footer_marg_right_x': 100,
        'footer_marg_bottom_y': 80,
        'footer_px_between_lines': 10,
        'write_header': True,
        'short_header': False,
        'write_tracts': True,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'megaplat_default': {
        'dim': (1700, 2200),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 120,
        'line_stroke': {
            -1: 8,
            0: 3,
            1: 1,
            2: 1,
            3: 1, None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (0, 0, 0, 255),
            2: (64, 64, 64, 96),
            3: (64, 64, 64, 24),
            None: (230, 230, 230, 24)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 38,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationMono-Bold.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 72,
        'footerfont_size': 28,
        'secfont_size': 24,
        'lotfont_size': 14,
        'headerfont_rgba': (192, 192, 192, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 36,
        'header_px_above_body': 15,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 100,
        'footer_marg_right_x': 100,
        'footer_marg_bottom_y': 80,
        'footer_px_between_lines': 10,
        'write_header': True,
        'short_header': True,
        'write_tracts': True,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'megaplat_s': {
        'dim': (1700, 2200),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 64,
        'line_stroke': {
            -1: 4,
            0: 0,
            1: 0,
            2: 0,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (64, 64, 64, 255),
            2: (64, 64, 64, 64),
            3: (64, 64, 64, 32),
            None: (230, 230, 230, 32)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 20,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationMono-Bold.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 48,
        'footerfont_size': 28,
        'secfont_size': 14,
        'lotfont_size': 14,
        'headerfont_rgba': (196, 196, 196, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 14,
        'header_px_above_body': 15,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 100,
        'footer_marg_right_x': 100,
        'footer_marg_bottom_y': 80,
        'footer_px_between_lines': 10,
        'write_header': True,
        'short_header': True,
        'write_tracts': True,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'megaplat_tiny': {
        'dim': (1, 1),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 32,
        'line_stroke': {
            -1: 2,
            0: 1,
            1: 1,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (128, 128, 128, 255),
            2: (64, 64, 64, 48),
            3: (64, 64, 64, 32),
            None: (230, 230, 230, 32)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 12,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationMono-Bold.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 24,
        'footerfont_size': 8,
        'secfont_size': 10,
        'lotfont_size': 1,
        'headerfont_rgba': (128, 128, 128, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (64, 64, 64, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 12,
        'header_px_above_body': 1,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 14,
        'footer_marg_right_x': 14,
        'footer_marg_bottom_y': 14,
        'footer_px_between_lines': 6,
        'write_header': True,
        'short_header': True,
        'write_tracts': False,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'square_l': {
        'dim': (1200, 1200),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 160,
        'line_stroke': {
            -1: 3,
            0: 2,
            1: 1,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (64, 64, 64, 255),
            2: (64, 64, 64, 96),
            3: (64, 64, 64, 64),
            None: (230, 230, 230, 24)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 48,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 48,
        'footerfont_size': 14,
        'secfont_size': 24,
        'lotfont_size': 12,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 120,
        'header_px_above_body': 18,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 20,
        'footer_marg_right_x': 20,
        'footer_marg_bottom_y': 20,
        'footer_px_between_lines': 7,
        'write_header': True,
        'short_header': False,
        'write_tracts': False,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'square_m': {
        'dim': (560, 560),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 80,
        'line_stroke': {
            -1: 3,
            0: 1,
            1: 1,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (64, 64, 64, 255),
            2: (32, 32, 32, 48),
            3: (64, 64, 64, 24),
            None: (230, 230, 230, 24)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 24,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 20,
        'footerfont_size': 14,
        'secfont_size': 14,
        'lotfont_size': 1,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (0, 0, 0, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 40,
        'header_px_above_body': 4,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 20,
        'footer_marg_right_x': 20,
        'footer_marg_bottom_y': 20,
        'footer_px_between_lines': 7,
        'write_header': True,
        'short_header': False,
        'write_tracts': False,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'square_s': {
        'dim': (416, 416),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 56,
        'line_stroke': {
            -1: 2,
            0: 1,
            1: 1,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (64, 64, 64, 196),
            2: (96, 96, 96, 112),
            3: (128, 128, 128, 32),
            None: (230, 230, 230, 32)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 20,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 18,
        'footerfont_size': 14,
        'secfont_size': 12,
        'lotfont_size': 12,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (64, 64, 64, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 40,
        'header_px_above_body': 3,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 14,
        'footer_marg_right_x': 14,
        'footer_marg_bottom_y': 14,
        'footer_px_between_lines': 7,
        'write_header': True,
        'short_header': False,
        'write_tracts': False,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },

    'square_tiny': {
        'dim': (216, 216),
        'qq_fill_rgba': (0, 0, 255, 100),
        'sec_length_px': 32,
        'line_stroke': {
            -1: 2,
            0: 1,
            1: 1,
            2: 1,
            3: 1,
            None: 1
        },
        'line_rgba': {
            -1: (0, 0, 0, 255),
            0: (0, 0, 0, 255),
            1: (128, 128, 128, 255),
            2: (64, 64, 64, 48),
            3: (64, 64, 64, 32),
            None: (230, 230, 230, 32)
        },
        'min_depth': 2,
        'max_depth': None,
        'centerbox_dim': 12,
        'lot_num_offset_px': 6,
        'headerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'footerfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'secfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'lotfont_typeface': '_fonts/LiberationSans-Regular.ttf',
        'headerfont_size': 10,
        'footerfont_size': 8,
        'secfont_size': 10,
        'lotfont_size': 1,
        'headerfont_rgba': (0, 0, 0, 255),
        'footerfont_rgba': (0, 0, 0, 255),
        'secfont_rgba': (64, 64, 64, 255),
        'lotfont_rgba': (0, 0, 0, 255),
        'warningfont_rgba': (255, 0, 0, 255),
        'body_marg_top_y': 12,
        'header_px_above_body': 1,
        'footer_px_below_body': 40,
        'footer_marg_left_x': 14,
        'footer_marg_right_x': 14,
        'footer_marg_bottom_y': 14,
        'footer_px_between_lines': 6,
        'write_header': False,
        'short_header': False,
        'write_tracts': False,
        'write_section_numbers': True,
        'write_lot_numbers': False,
        'lots_only_for_queue': False,
    },
}
